name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - master  # Trigger on pushes to master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to push to gh-pages

      # Step 2: Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2  # Match your local Ruby version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Step 4: Clean and build Jekyll site
      - name: Build site
        run: |
          bundle exec jekyll clean
          bundle exec jekyll build

      # Step 5: Deploy to gh-pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          commit_message: "Deploy site from GitHub Actions"